version: '3.9'
services:
  mongo:
    image: mongo:6.0.6
    container_name: api_database
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/mongo-init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
  climate_api:
      build:
        context: ./app
        dockerfile: Dockerfile
      image: climate_api
      container_name: climate_api
      command: gunicorn app.core.app:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
      restart: always
      depends_on: [mongo]
      env_file:
        - .env
      environment:
        MONGODB_HOST: mongo
      ports:
        - "8000:8000"