version: '3.9'
services:
  mongo:
    image: mongo:6.0.6
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/mongo:/data/db
      - ./data/mongo-init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
  climate_api:
      build:
        context: ./
        dockerfile: app.Dockerfile
      volumes:
        - './app:/app'
      ports:
        - 8000:8000
      env_file:
        - .env