name: climATe API

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions: write-all

jobs:
  test:
    name: 'Code quality and test'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.6]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest pytest-cov
          if [ -f app/requirements-dev.txt ]; then pip install -r app/requirements-dev.txt; fi
          if [ -f api_data_processing/requirements-dataprocessing.txt ]; then pip install -r api_data_processing/requirements-dataprocessing.txt; fi
      - name: Static Code Linting with ruff
        run: |
          # default set of ruff rules with GitHub Annotations
          ruff --format=github --target-version=py37 .
        continue-on-error: true
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: '6.0'
      - name: Test with pytest
        run: |
          pytest --cov-config=.coveragerc --cov-report term --cov-report html:htmlcov --cov=app app/tests
          coverage-badge -o htmlcov/coverage.svg
      - name: Upload code coverage html report
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: htmlcov

  release:
    name: 'Release to GitHub'
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18
    - name: Add plugin for conventional commits
      run: npm install conventional-changelog-conventionalcommits
      working-directory: ./.github/workflows
    - name: Release to GitHub
      working-directory: ./.github/workflows
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_AUTHOR_NAME: Janos Tordai
        GIT_AUTHOR_EMAIL: tjanos88@gmail.com
        GIT_COMMITTER_NAME: Janos Tordai
        GIT_COMMITTER_EMAIL: tjanos88@gmail.com
      run: npx semantic-release
  patch:
    name: 'Bump version number if needed and tag'
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Bump major
        if: contains(github.event.head_commit.message, '!major')
        id: AutoTaggerMajor
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: major
      - name: Bump minor
        if: contains(github.event.head_commit.message, '!minor')
        id: AutoTaggerMinor
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: minor
      - name: Bump patch
        if: contains(github.event.head_commit.message, '!patch')
        id: AutoTaggerPatch
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch