name: climATe API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.6]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest pytest-cov
          if [ -f app/requirements-dev.txt ]; then pip install -r app/requirements-dev.txt; fi
          if [ -f api_data_processing/requirements-dataprocessing.txt ]; then pip install -r api_data_processing/requirements-dataprocessing.txt; fi
      - name: Static Code Linting with ruff
        run: |
          # default set of ruff rules with GitHub Annotations
          ruff --format=github --target-version=py37 .
        continue-on-error: true
      - name: Test with pytest
        run: |
          pytest --doctest-modules --junitxml=junit/test-results-${{ matrix.python-version}}.xml --cov=com --cov-report=xml --cov-report=html
      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: junit/test-results-${{ matrix.python-version }}.xml
        if: ${{ always() }}
  release:
    name: 'Release to GitHub'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18
    - name: Add plugin for conventional commits
      run: npm install conventional-changelog-conventionalcommits
      working-directory: ./.github/workflows
    - name: Release to GitHub
      working-directory: ./.github/workflows
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_AUTHOR_NAME: Janos Tordai
        GIT_AUTHOR_EMAIL: tjanos88@gmail.com
        GIT_COMMITTER_NAME: Janos Tordai
        GIT_COMMITTER_EMAIL: tjanos88@gmail.com
      run: npx semantic-release